name: Build Android

on:
  release:
    types: [created]

permissions:
  actions: write
  contents: write
  deployments: write

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          set-safe-directory: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://npm.pkg.github.com'

      - name: Update Package.json version
        uses: jossef/action-set-json-field@v2.1
        with:
          file:  projects/ng-adblock-detect/package.json
          field: version
          value: ${{ github.event.release.tag_name }}

      - name: Install app dependencies
        run: npm ci

      - name: Build Svelte app
        run: yarn build
        run: cd dist/ng-adblock-detect

      - name:  Publish Package in github
        run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
